products = [
    {
        '_id': '1',
        'name': 'Otomatik Portakal',
        # 'image': '',
        'author': 'Anthony Burgess',
        'publisher': 'İş Bankası Kültür Yayınları',
        # 'category': '',
        'translator': 'Aziz Üstel',
        'price': 20.40,
        'countInStock': 10,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Sineklerin Tanrısı',
        # 'image': '',
        'author': 'William Golding',
        'publisher': 'İş Bankası Kültür Yayınları',
        # 'category': '',
        'translator': 'Mina Urgan',
        'price': 32.40,
        'countInStock': 20,
        'numReviews': 25,
    },
    {
        '_id': '3',
        'name': 'Suç ve Ceza',
        # 'image': '',
        'author': 'Fyodor Mihayloviç Dostoyevski',
        'publisher': 'Can Yayınları',
        # 'category': '',
        'translator': 'Sabri Gürses',
        'price': 64.60,
        'countInStock': 50,
        'numReviews': 45,
    },
    {
        '_id': '4',
        'name': 'Silmarillion',
        # 'image': '',
        'author': 'J. R. R. Tolkien',
        'publisher': 'İthaki Yayınları',
        # 'category': '',
        'translator': 'Berna Akkıyal',
        'price': 114.00,
        'countInStock': 8,
        'numReviews': 6,
    },
    {
        '_id': '5',
        'name': 'Bülbülü Öldürmek',
        # 'image': '',
        'author': 'Harper Lee',
        'publisher': 'Epsilon Yayınevi',
        # 'category': '',
        'translator': 'Ülker İnce',
        'price': 81.80,
        'countInStock': 50,
        'numReviews': 47,
    },
    {
        '_id': '6',
        'name': 'Şeker Portakalı',
        # 'image': '/images/alexa.jpg',
        'author': 'Jose Mauro De Vasconcelos',
        'publisher': 'Can Yayınları',
        # 'category': '',
        'translator': 'Emrah İmre',
        'price': 51.00,
        'countInStock': 0,
        'numReviews': 12,
    },
]