# Generated by Django 4.1.7 on 2023-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_order_totalprice_orderitem_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='totalPrice',
        ),
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
